- python/lsst/ctrl/mpexec/taskFactory.py
This avoids expensive searches and importing of too many modules.
> DM-17044: Require module name with task name

- python/lsst/ctrl/mpexec/cmdLineParser.py
- tests/test_cmdLineParser.py
For consistency with other options that use task labels switching to
colon as a separator for -c option value.
> DM-17041: Use colon instead of dot with -c option

- python/lsst/ctrl/mpexec/cmdLineParser.py
- tests/test_cmdLineParser.py
Now the value of --dataset-name-substitution is parsed directly during
command line parsing. Added unit tests for that new feature too.
Fix parsing of dataset-name-substitution option.
> Parse dictionary in command line parser (DM-17067)

- python/lsst/ctrl/mpexec/taskLoader.py
DM-17148 changed the way the modules were imported and that broke
pickle. Need manual adding of modules to `sys.modules` to make things
work again.
> DM-17720: Fix pickle issue

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
We're about to use 'prerequisite' to mean something else in a more public context.
> DM-16539: Switch nomenclature from 'prerequisite' to 'dependency'.

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
Trivial change to the code. Also adds less trivial unit test for these
checks to validate validation. CmdLineFwk unit tests will be expanded
later with more tests for other methods (some will need reasonable
registry contents).
> DM-17932: Validate object type when reading objects from pickle

- python/lsst/ctrl/mpexec/cmdLineFwk.py
See https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for format characters.
> DM-19769: Fix time logging with --longlog.

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- python/lsst/ctrl/mpexec/examples/calexpToCoaddTask.py
- python/lsst/ctrl/mpexec/examples/make_example_qgraph.py
- python/lsst/ctrl/mpexec/examples/patchSkyMapTask.py
- python/lsst/ctrl/mpexec/examples/rawToCalexpTask.py
- python/lsst/ctrl/mpexec/examples/test1task.py
- python/lsst/ctrl/mpexec/examples/test2task.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- python/lsst/ctrl/mpexec/util.py
- tests/config/butler.yaml
- tests/testUtil.py
- tests/test_cmdLineFwk.py
- tests/test_cmdLineParser.py
With `--skip-existing` option we now also support skipping Quanta at run time so that the same QGraph can be executed again after unfinished previous attempt and it will effectively restart execution from the point where it stopped previously. Just as before `--skip-existing` during QGraph generation means skipping Quanta whose outputs already exist.
New option `--clobber-output` can be used to override datasets that exist in output collection:
- when generating QGraph all existing outputs are ignored (including regular outputs and initOutputs),
- when executing QGraph the existing outputs are removed prior to Quantum execution.
> DM-20845: Support re-run of pipetask on the same output collection

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
Un-pickling of QGraph requires dimension universe to be initialized,
this patch instantiates data butler to initialize registry for that
effect.
> Fix un-pickling of qgraph (DM-21724).

- python/lsst/ctrl/mpexec/dotTools.py
This ensures qGraph dot files are constructed properly, as the text
labels were raising previously.
> DM-21843: Wrap Dimension keys in str() to prevent errors.

- python/lsst/ctrl/mpexec/cmdLineParser.py
- tests/test_cmdLineParser.py
Single-letter options are made unique:
- `list` subcommand only uses long options now
- timeout option also uses long option
- `-p pipeline.pickle` is replaced with `-r pipeline.pickle`
> DM-21889: Avoid option reuse in pipetask

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
Fix config overrides handling.
Both -c and -C options had issues after latest refactoring of pipeline
interfaces, should be fixed now. Added unit test to check the expected
behavior.
> DM-22177: ctrl_mpexec calls non-existent Pipeline.addConfigOverrideFile method

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- tests/test_cmdLineFwk.py
There was a type in action name and also a bug in logic introduced in
one of the recent commits, should be fixed now.
> DM-22198: pipetask qgraph Unexpected pipeline action: new_instrument

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/util.py
- tests/test_cmdLineFwk.py
The code still expected pipeline to be a list of TaskDefs which is not
true anymore, need to call special method to get that list. Added unit
tests to check --show options and fixed all cases needed for correct
functioning.
> DM-22166: Fix pipetask --show=pipeline option

- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
It never made sense for DatasetRefs without IDs to have components with IDs, and now DatasetRef guarantees that components is None if the ID is None.
> DM-21448: Don't look for components of unresolved datasets.

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- python/lsst/ctrl/mpexec/examples/calexpToCoaddTask.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
- tests/test_cmdLineParser.py
The --debug option existed but did not do anyhting, added code that
imports `debug.py` when that option is set. Compared to CmdLineTask in
`pipetask` I do it in two places, once before PreExecInit (in case
someone needs to debug task construction) and once before running each
task. Latter is not needed if `multiprocess` uses 'fork' start method
but it is impossible to guarantee that is always true on all platforms.
> DM-22504: Support for lsstDebug functionality in Gen3 middleware

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
The `--show=config` option now prints configuration without imports. New
option `--show=dump-config[=Task]` now dumps complete configuration for
a task (or all tasks) with all imports.
Config history option was improved as well, one can use natural configuration
syntax for configurable fields, exactly as it appears in config overrides, e.g.
`--show history="measurePsf.psfDeterminer['pca'].lam"`.
> DM-22301: Improve printing of task configs

- python/lsst/ctrl/mpexec/cmdLineParser.py
- tests/test_cmdLineParser.py
Implemented special action class to replace special type used for
`--input` option before. New action class can handle multiple options
and collects all collection names from all options into a single
dictionary. Special care is needed to not modify default value if that
is passed to argument definition. Unit test extended to cover new
functionality.
> DM-23212: Add support for multiple -i options

- python/lsst/ctrl/mpexec/cmdLineParser.py
Fix help string for pipeline parameters. 
This was forgotten during migration to new pipeline definition format.
QGraph is still saved in pickle and read from pickle too.
> DM-23635: Confusing help text for pipetask

- python/lsst/ctrl/mpexec/__init__.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- python/lsst/ctrl/mpexec/execFixupDataId.py
- python/lsst/ctrl/mpexec/executionGraphFixup.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
- tests/test_cmdLineParser.py
- tests/test_executors.py
Executor classes have been refactored to better separate concerns. An
optional "graph fixup" instance can be passed to graph executor which
allows some modifications of the execution graph (e.g. changing
dependencies between quanta). Command line now has an option to import
and instantiate graph fixup object and pass it to executor. Unit test
was added to verify new functionality.
> DM-24370: Support extensible scheduling in pipetask

- python/lsst/ctrl/mpexec/dotTools.py
- tests/test_dotTools.py
Adds quotes around each node name. Simple test case was implemented for
pipeline graph, but I don't have quantum graph in that test. I checked
that quantum graph dot file looks good by running a trivial example.
> DM-24796: Quote node names in graphviz dot files

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- python/lsst/ctrl/mpexec/executionGraphFixup.py
- python/lsst/ctrl/mpexec/preExecInit.py
- tests/testUtil.py
- tests/test_cmdLineFwk.py
- tests/test_cmdLineParser.py
PreExecInit now saves task configurations for every task in a pipeline,
the names of dataset types are fixed as `{taskLabel}_config`. It also saves
package versions in a dataset with fixed type name "packages". Dataset
types are registered together with all other dataset types when 
--register-dataset-types option is specified.
> DM-24797: Store per-run information (configs, software versions) in butler repo

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
When reading QuantumGraph from pickle DimensionUniverse instance must be
initialized, this fix makes registry instance before un-pickling which
creates all necessary instances. This trivial fix exposed an issue with
my dumb unit test that also needed proper fix.
> DM-25016: Fix reading of QuantumGraph from pickle file

- python/lsst/ctrl/mpexec/preExecInit.py
- tests/testUtil.py
- tests/test_preExecInit.py
PreExecInit expected butler.get() to return None for missing datasets,
while in reality it raises LookupError. Fixing this and also adding unit
test for this.
> DM-25222: Fix handling of skip-existing in PreExecInit

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
Before executing a task scan its dataIds and see if they have an
instrument name, if so then make instrument instance which initializes
filter singleton with all instrument filters.
> DM-26181: Ensure that filters are defined in pipetask

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- tests/testUtil.py
- tests/test_cmdLineFwk.py
- tests/test_executors.py
Catches TimeoutError and makes a new exception with more context info
about task and quantum. Unit test extended to simulate that case.
> DM-26230: Improve pipetask dignostics on timeouts

- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- tests/test_cliCmd.py
- tests/test_cmdLineFwk.py
- tests/test_cmdLineParser.py
- tests/test_executors.py
Replaced use of multiprocessing Pool with manual process management based on `Process` class. Crashes in sub-processes should be handled correctly now. Exceptions are not propagated to main process, they will appear in the log when subprocess fail, main process will just list all tasks that failed.
Implemented "keep running" as default option, there is new command line option `--fail-fast` which turns on old behavior.
> DM-26136: Improve handling of crashes in pipetask

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
My previous workaround for passing butler to subprocess was broken
because new connection was made in the parent process. Replacing with a
new workaround that passes butler in pickle form across fork.
> Fix Postgres connection error in multi-process case (DM-26539)

- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/cmdLineParser.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/testUtil.py
- tests/test_cliScript.py
- tests/test_cmdLineFwk.py
- tests/test_cmdLineParser.py
- tests/test_preExecInit.py
Extended executor to remove partial outputs if this option is specified.
Added unit test for this new feature, made some refactoring in unit
tests to use true butler instead of my own mock.
> DM-26131: Add --clobber-partial-outputs option to pipetask

- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
(I notice that pipetask (non-click) does support `@file` for this).
Requires lsst/daf_butler#377
> DM-26780: Enable -@ for reading command line options

- tests/test_cmdLineFwk.py
This partially reverts 75fc90fb5a6ea285e7c9459854d7fa4d9a8d567e.
> DM-27390: un-adapt to some daf_butler API changes I thought better of.

- tests/test_executors.py
Increases time for which a long running task runs so that it does not
finish before failing task fails.
> Fix failfast unit test timing issue (DM-27381)

- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
I tried to find a better way to navigate Config structure but in the end
decided that `eval` is the easiest and most natural way to do it.
I did not want to parse the printed attribute representation myself (do
not want to re-implement `eval`) and navigating Config class hierarchy
needs too much effort.
> DM-27519: Improve printing of config history

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
Supports python 3.8 on mac, which defaults to spawn method.
> Use multiprocessing context with fork method

- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/build.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cli/utils.py
PipetaskCommand class allows pipetask-specific overrides of
subcommand behaviors.
This adds a comment to the end of every subcommand's help text,
that more options are available using "pipetask --help"
Removes the --log-level option from subcommands.
There was other help text in the epilog that was specific to
prototype development of chained subcommands, and should have
been removed when we did not use that feature. It is now
removed.
> DM-27500: add a comment in butler & pipetask subcommand about more options in butler --help

- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_executors.py
Pipetask has new option --start-method which tkaes the name of the start
method from multiprocessing (spawn, fork, forkserver). Default method is
now set as "spawn" on MacOS and "fork" on Linux. Some care was needed
when unpickling dimensions, this has to be done after unpickling
registry. Unpickling is ordered manually now. As usual logging causes
issues, with spawn it needs to be re-initialized in every child, added
support for recording and replaying configuration (part of that is in
`daf_butler`).
> DM-27118: Add support for spawn start method

- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
In theory this would allow a graph pickle file to be read from S3.
> DM-27682: Switch quantum graph load/save to using URIs

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
Moved the message to a method which only runs in multiprocessing mode,
changed it to debug instead of info.
> Fix confusing message from pipetask run (DM-27840)

- .gitignore
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
New option `--qgraph-node-id` is added which takes a bunch of integers
for node numbers to execute from a full graph. Another new option
`--qgraph-id` can be used to specify graph ID to verify it after loading
from pickle file.
> DM-27667: Add pipetask option to execute graph subset

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
Multiprocessing scheduler did not scale very well with the number of
nodes in a quantum graph. Re-designed data structures to avoid looping
through the list of nodes on every iteration.
> DM-28418: Improve scheduler performance for large graph

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
This allows passing Butler to a subpocess without pickling it when using
fork start method.
> DM-26302: Use new registry method to reset connection pool.

- python/lsst/ctrl/mpexec/execFixupDataId.py
- tests/test_executors.py
This PR updates the `ExecFixupDataId` class and its unit tests to correct some bit-rotting that occurred since it was first written.
> DM-12549: ap_pipe must call AssociationTask in a reproducible order

- doc/conf.py
- doc/lsst.ctrl.mpexec/index.rst
- doc/lsst.ctrl.mpexec/pipetask.rst
The rST content was severely bitrotted.  I'm not sure what was going on with the conf.py, but sphinx couldn't find its click extensions
without this change, which is just mindless cargo-culting from daf_butler.
> DM-28598: Fix pipetask command-line utility doc generation.

- COPYRIGHT
- python/lsst/ctrl/mpexec/taskFactory.py
- tests/test_taskFactory.py
This PR fixes a name collision inadvertently introduced in #122, and adds unit tests to catch similar bugs in the future.
> DM-30148: PipelineTasks use wrong label as name

- doc/changes/DM-30702.misc.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- [ x ] ran Jenkins - https://ci.lsst.codes/job/stack-os-matrix/34456/display/redirect
- [ x ] added a release note for user-visible changes to `doc/changes`
> Tickets/DM-30702 Add metadata to QuantumGraph

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
The recent NoWorkFound changes were intended to let a Quantum
continue to run if some of its inputs were missing as long as
enough inputs were present. However, there was a bug related
to wrong dataset types and use of defaultdict that caused the
system to always think NO inputs were present if any were
missing. This fixes that.
For those interested, adjustQuantum on a connections class indexes
things by dataset type name, a string. Most other paces use
DatasetType object in mappings. This is not a problem with
NameDict containers because they know how to translate. However in
this case a defaultdict was used to construct the mapping, and the
keys were all DatasetTypes.
Then this was passed through to update the Quantum and adjust it.
Because the container type was still defaultdict, when …
> Dm-31054 Fix issue running Quantum when inputs are missing

- doc/changes/DM-30977.feature.rst
- python/lsst/ctrl/mpexec/cli/pipetask.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cliScript.py
- tests/test_cmdLineFwk.py
Relies on lsst/daf_butler#546 and lsst/pipe_base#193
> DM-30977: Accumulate log messages per quantum and store in butler

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
Add special logic to detect cases when we don't want to save log records
to butler. Removes temporary file in that case or when ingest does not
work. When ingest is not supported we now store an empty records object
to make sure that dataset exists for consistency with other cases.
> DM-31255: Fix log-to-butler failures with --skip-existing

- doc/changes/DM-27492.feature.md
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
- tests/test_preExecInit.py
Several improvements in `pipetask` execution options:
- New option `--skip-existing-in` which takes collection names(s), if output
datasets already exist in those collections corresponding quanta is skipped.
- A `--skip-existing` option is now equivalent to appending output run
collection to the `--skip-existing-in` list.
- An `--extend-run` option implicitly enables `--skip-existing` option.
- A `--prune-replaced=unstore` option only removes regular output datasets;
InitOutputs, task configs, and package versions are not removed.
> DM-27492: Improvements to pipetask execution options

- doc/changes/DM-31884.feature.rst
- python/lsst/ctrl/mpexec/cli/pipetask.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
Requires lsst/daf_butler#557
Adds the output RUN to every record and also now supports the `--log-label` command.
> DM-31384: Add extra information to log record

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
tempfile forces restrictive permission on all files and this
can cause read permissions later in the datastore.
> DM-31579: Force temp file for log collection to have normal file protections

- doc/changes/DM-31691.bugfix.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
Include output collection in call to buildExecutionButler.
> DM-31691: Fix call to buildExecutionButler.

- doc/changes/DM-31711.bugfix.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
> DM-31711: Fix call to buildExecutionButler when chained input collection.

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
It's much easier for provenance tracking if the UUID of the dataset always matches the one generated during initial creation of the execution butler. When clobbering the output datasets because of a resubmission of a failed job the pruneDatasets call was purging the records and deleting the files. This results in entirely new UUIDs being used when the new dataset
is put in the butler.  Modify the logic to not purge if it seems that an execution butler is being used.
> DM-31941: Do not purge datasets when clobbering in execution butler

- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
It was moved there so it could be used by daf_butler.
> DM-31976: (v23) Use register-dataset-types option from daf_butler now

- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/examples/calexpToCoaddTask.py
- python/lsst/ctrl/mpexec/examples/patchSkyMapTask.py
- python/lsst/ctrl/mpexec/examples/rawToCalexpTask.py
- python/lsst/ctrl/mpexec/examples/test1task.py
- python/lsst/ctrl/mpexec/examples/test2task.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- python/lsst/ctrl/mpexec/taskFactory.py
> DM-31801: Change logger name to retain the lsst. prefix

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
Uses private pipe_base global to determine this during the transition period.
Requires lsst/pipe_base#211
> Use same metadata class as pipe_base is using

- python/lsst/ctrl/mpexec/preExecInit.py
- tests/config/datastores/fileDatastore.yaml
- tests/config/storageClasses.yaml
- tests/test_simple_pipeline_executor.py
Depends on lsst/daf_butler#635 and lsst/pipe_base#228
> DM-33303: Tests for pipelines where Task and Butler disagree on DatasetType

- doc/changes/DM-33339.misc.md
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
In a single-process mode the MPGraphExecutor will try to execute remaining
tasks after one of the tasks fails (skipping the tasks that depend on
outputs of failed tasks) instead of exiting on an exception. This needed
some changes in exception handling, instead of passing an original
exeption raised by a task, it now raises MPGraphExecutorError, this is
consistent with multi-process case. Task timeouts are not handled in
single-process case.
> Continue execution after task failure (DM-33339)

- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/dataid_match.py
- python/lsst/ctrl/mpexec/mock_task.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
- tests/test_dataid_match.py
`pipelinetask` adds a --mock option, with that option enabled the framework
skips calling task runQuantum method and instead executes a special method
that writes provenance data as dictionaries. With this it is possible to run
the whole ci_hsc_gen3 pipeline in a mock mode which executes much faster.
Options --config and --config-file can specify task label as "{label}-mock",
this applies config overrides to mock tasks matching corresponding label. Mock
task has two config fields - `failCondition` which specifies condition for
generating an exception, and `failException` which specifies exception class
name.
> DM-31253: Implement mock pipeline execution

- python/lsst/ctrl/mpexec/preExecInit.py
- tests/test_simple_pipeline_executor.py
Rather than only reporting the first unregistered dataset
type, report all of them.
> DM-33569: Report all missing dataset types

- doc/changes/DM-33481.feature.md
- python/lsst/ctrl/mpexec/__init__.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/reports.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_executors.py
- tests/test_reports.py
Added couple of pydantic data structures that contain data to save in
jobreport.json. `pipetask` adds a `--summary` option specifyng file
name for jobreport. Naturally pipetask cannot produce complete report,
in particular `exitCode` cannot be filled by the process before it
exits. Some post-processing of the generated file will be needed to
finalize it.
> DM-33481: Add support for jobreport

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- tests/test_executors.py
Detect the case when a task manages to finish successfully before it
gets killed due to timeout. This guarantees more consistent status in
a quantum report.
Increase running time for timed out task in a unit test. 
Running time for timing-out task increased to 100 seconds, this should
reduce the chance for it to finish successfully before timeout is
detected by a parent.
> DM-34076: Improve timeout handling by MPGraphExecutor

- .github/workflows/build.yaml
- doc/changes/DM-34105.feature.rst
- python/lsst/__init__.py
- python/lsst/ctrl/__init__.py
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/utils.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/examples/calexpToCoaddTask.py
- python/lsst/ctrl/mpexec/examples/rawToCalexpTask.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- requirements.txt
- setup.cfg
- setup.py
- tests/test_cmdLineFwk.py
- tests/test_taskFactory.py
- ups/ctrl_mpexec.table
* Use pipe_base for Instrument
* Remove afw from test and examples.
Requires lsst/pipe_base#239
> DM-34105: Clean up dependencies

- doc/changes/DM-34215.feature.rst
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
When we get an exception, sometimes it's not enough to just
see the backtrace, but we also want to get a debugger prompt
at the point of the exception.
Replaced the --do-raise option (apparently unused, and often
associated with getting a debugger with Gen2) with --pdb
(well-known and appreciated option from pytest), which causes
MPGraphExecutor._executeQuantaInProcess to drop into pdb.
> DM-34215: Support dropping into debugger on exception

- doc/changes/DM-34261.bugfix.rst
- python/lsst/ctrl/mpexec/cli/opt/options.py
> DM-34261: respond to click.Path api change

- doc/changes/DM-33634.feature.rst
- python/lsst/ctrl/mpexec/cli/cmd/__init__.py
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/__init__.py
- python/lsst/ctrl/mpexec/cli/opt/arguments.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/__init__.py
- python/lsst/ctrl/mpexec/cli/script/cleanup.py
- python/lsst/ctrl/mpexec/cli/script/confirmable.py
- python/lsst/ctrl/mpexec/cli/script/purge.py
- tests/config/metricTestRepoButler.yaml
- tests/test_cliCmdCleanup.py
- tests/test_cliCmdPurge.py
> DM-33634: Add pipetask purge and cleanup subcommands

- tests/test_cliScript.py
> DM-34155: Expect fully-qualified task names in TaskDef.

- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
`pipetask` adds new command line option to enable storing of the dataset
records in quanta.
> DM-33493: Add datastore records to generated quantum graph

- tests/test_cmdLineFwk.py
"1" is a valid upstream dimension version so the
namespace is needed to disambiguate.
Requires lsst/daf_butler#683
> DM-33946: Add a namespace to the test universe configuration

- doc/changes/DM-34811.bugfix.md
- python/lsst/ctrl/mpexec/dotTools.py
- tests/test_dotTools.py
Creating a dot graph was previously not correctly linking component
datasets to the composite that provided them when drawing a graph,
this ensures the linkages are added appropriately.
- [ x ] ran Jenkins
- [ x ] added a release note for user-visible changes to `doc/changes`
> DM-34811 Fix component linkages in pipeline dot render

- .github/workflows/build.yaml
- requirements.txt
- setup.cfg
> DM-35047: Add upload to pypi

- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
The output collection should be first in the list of collections, not last.
> DM-35153: Fix collection order in SimplePipelineExecutor

- setup.cfg
> DM-35047: Add entry point in setup.cfg for pipetask

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- setup.cfg
The `pruneDatasets` Butler method dropped `run` argument, removing it
from the client side. Execution butler logic is now handled internally
in the same method, removing this logic from caller.
> DM-33488: Update for changes in pruneDatasets interface

- .github/workflows/build.yaml
- python/lsst/ctrl/mpexec/mock_task.py
> DM-35971: Pytest requires flake<5

- .github/workflows/build.yaml
- README.rst
- doc/changes/DM-31769.feature.rst
- doc/changes/DM-31966.misc.md
- doc/changes/DM-32408.feature.rst
- doc/changes/DM-33481.feature.md
- doc/changes/DM-33634.feature.rst
- doc/changes/DM-34105.feature.rst
- doc/changes/DM-34215.feature.rst
- doc/changes/DM-34261.bugfix.rst
- doc/changes/DM-34811.bugfix.md
- doc/lsst.ctrl.mpexec/CHANGES.rst
- pyproject.toml
- python/lsst/ctrl/mpexec/mock_task.py
- python/lsst/ctrl/mpexec/taskFactory.py
- requirements.txt
> DM-36034: v24.0.0 release notes

- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- tests/test_cmdLineFwk.py
By moving the exception raise down to the outer click layer (returning None through all higher layers) we avoid the long traceback that hides the useful information being logged by pipe_base.
I expect the `build_and_test` check here to fail until the pipe_base is branch is merged.
> DM-36360: Improve diagnostic visibility for empty QGs.

- doc/changes/DM-36412.feature.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
> DM-36412: Try to set the datastore cache directory explicitly

- doc/changes/DM-36145.feature.md
- python/lsst/ctrl/mpexec/cmdLineFwk.py
> DM-36145: Add additional quanta information for pipetask run

- doc/changes/DM-36487.api.md
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
SimplePipelineExecutor factory methods add a parameter for a bind mapping and pass it to GraphBuilder.
> DM-36487: Support bind values with user query in SimplePipelineExecutor

- doc/changes/DM-36831.feature.md
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
The new --enable-implicit-threading option to "pipetask run" can be used to turn it back on.
> DM-36831: Disable implicit threading in pipetask by default.

- python/lsst/ctrl/mpexec/cli/utils.py
- tests/test_simple_pipeline_executor.py
New butler code causes the storage class in the DatasetType passed to findDataset to be respected, which causes the storage class in the input connection to be respected.
Relies on lsst/daf_butler#766
> DM-37450: Fix text with faulty expectations.

- doc/changes/DM-37582.feature.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
Execution butler builder is updated (on this ticket) to support resolved refs for outputs. This allows us to always resolve all refs in generated graphs.
Depends on lsst/pipe_base#299
> DM-37582: Always resolve dataset refs in generated graph

- python/lsst/__init__.py
- python/lsst/ctrl/__init__.py
> DM-37552: Remove unnecessary lsstimport import

- doc/changes/DM-34420.feature.md
- mypy.ini
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/cmd/coveragerc
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
> [DM-34420] Turn on coverage option

- python/lsst/ctrl/mpexec/cli/cmd/commands.py
> DM-38081: Fix for coverage option passed to run_qbb

- tests/test_executors.py
Apparently `faulthandler` is now enabled by default (which is a good thing in general) and it prints a long confusing traceback for the unit test that uses signal to kill a task. Disabling `faulthandler` in that task is sufficient to suppress traceback.
> DM-38165: Suppress traceback for a crashing task in unit test

- .github/workflows/build_docs.yaml
- doc/changes/DM-35494.feature.md
- doc/changes/DM-35917.feature.rst
- doc/changes/DM-36145.feature.md
- doc/changes/DM-36412.feature.rst
- doc/changes/DM-36487.api.md
- doc/changes/DM-36831.feature.md
- doc/lsst.ctrl.mpexec/CHANGES.rst
> DM-38065: v25 release notes

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/log_capture.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- python/lsst/ctrl/mpexec/taskFactory.py
- tests/test_cmdLineFwk.py
> DM-38210: Use butler.get() rather than deprecated getDirect()

- doc/changes/DM-38601.bugfix.md
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_executors.py
The logic in the method has been improved to handle the case when
clobberOutputs was specified without skipExistingIn. It now correctly
removes complete quantum outputs. Added test cases for this behavior.
> DM-38601: Fix checkExistingOutputs method to clobber complete outputs

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- requirements.txt
The bug causes occasional issues with multi-process pipeline executions with pytest using concurrent running. This is a known issue (https://github.com/python/cpython/issues/102512) which will eventually be fixed in Python, at that time the patch should become no-op and can be removed.
> DM-38669: Add workaround for Python threading bug

- doc/changes/DM-36162.feature.md
- python/lsst/ctrl/mpexec/__init__.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- tests/pipeline_separable.yaml
- tests/test_separablePipelineExecutor.py
This PR adds a new executor, `SeparablePipelineExecutor`, to `ctrl_mpexec`. This executor adopts elements of, and can be considered intermediate between, `SimplePipelineExecutor` and `CmdLineFwk`. The test suite is based on that for `SimplePipelineExecutor`, and can't test some capabilities (e.g., restricting input data IDs); more tests will be added later.
> DM-36162: Implement SeparablePipelineExecutor

- python/lsst/ctrl/mpexec/mock_task.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
> DM-37703: Catch unresolved refs warnings and some workarounds

- doc/changes/DM-38780.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/__init__.py
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/arguments.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/__init__.py
- python/lsst/ctrl/mpexec/cli/script/update_graph_run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cliCmdUpdateGraphRun.py
- tests/test_separablePipelineExecutor.py
The new command takes existing serialized quantum graph file, updates
output run and dataset IDs for all output datasets and writes updated
graph to a new file.
Fixes clobbering logic in SingleQuantumExecutor.
Few additional small updates related to changes in graph builder interface.
> DM-38780: Add new CLI sub-command to update output run in a graph 

- doc/changes/DM-38779.misc.rst
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- requirements.txt
- tests/test_cmdLineFwk.py
- tests/test_executors.py
This seems to be a real problem that is present in `pipetask run` itself but which we mask because the current code unresolves refs on put. The problem is that:
* makeGraph reads the supplied args, determines a time-stamped output run, and uses that to build the graph.
* runPipeline takes the graph and the args but uses the args to make a time-stamped output run.
* If the second has ticked over the output run is now different than the one used for the graph.
* singleQuantumExecutor runs and when Butler.put happens it unresolves the refs in the graph so that the timestamped RUN in the ref gets cleared and instead the butler's default RUN is used (and new UUID is issued).
I was expecting the unresolving to go away in #233 but we decided to leave that in place for now.
Fixing the tests is …
> DM-38779: Try to fix output run inconsistency

- requirements.txt
This reverts commit b5110ba0e188470979f893ce3b4db42b28c803c8. It was never meant to be merged.
> DM-38779: Remove the pipe_base special branch request

- doc/changes/DM-39122.doc.md
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mock_task.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
Additionally PreExecInit is cleaned up to always expect resolved refs in quantum graph and use those refs to store initOutputs. `CmdLineFwk` now checks that output runs on command line and in graph are consistent.
> DM-39122: Remove UnresolvedRefWarning filters

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/log_capture.py
- python/lsst/ctrl/mpexec/mock_task.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
All dataset references are resolved now, removing code that handled
unresolved refs.
ButlerQC now works with LimitedButler, there is no need for special case
for the full Butler.
> DM-37704: Remove use of unresolved refs.

- pyproject.toml
- python/lsst/ctrl/mpexec/cmdLineFwk.py
It was a nested method before and that interfered with pickle in multiprocessing on MacOS. Moved that to a separate callable class.
> DM-39434: Move QBB factory to a separate class

- doc/changes/DM-39377.misc.md
- pyproject.toml
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cliScript.py
> DM-39377: Assume that we always store task metadata

- tests/test_taskFactory.py
> DM-4037: Require non-empty doc string for config parameters

- .github/workflows/docstyle.yaml
- pyproject.toml
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/pipetask.py
- python/lsst/ctrl/mpexec/cli/script/build.py
- python/lsst/ctrl/mpexec/cli/script/cleanup.py
- python/lsst/ctrl/mpexec/cli/script/confirmable.py
- python/lsst/ctrl/mpexec/cli/script/pre_exec_init_qbb.py
- python/lsst/ctrl/mpexec/cli/script/purge.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cli/script/run_qbb.py
- python/lsst/ctrl/mpexec/cli/utils.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/dotTools.py
- python/lsst/ctrl/mpexec/execFixupDataId.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/reports.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/showInfo.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- python/lsst/ctrl/mpexec/util.py
- tests/test_cliCmdPurge.py
- tests/test_cmdLineFwk.py
- tests/test_simple_pipeline_executor.py
> DM-39605: Use butler.dimensions rather than butler.registry.dimensions

- doc/changes/DM-39294.misc.md
- python/lsst/ctrl/mpexec/dotTools.py
- tests/test_dotTools.py
> DM-39294: Refresh directed graph colors

- doc/changes/DM-39672.feature.md
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
> DM-39672: make it possible to force failures in mock pipelines on the command-line

- tests/test_simple_pipeline_executor.py
All of these tasks (modeled on lsst.pipe.base.tests.NoDimensionsTask, which is also in use here) were using their 'outputSC' config field to change the pytype they returned without adjusting their connection definition accordingly, and in one case that meant testing for the wrong behavior.
I've also changed the default value for 'outputSC' from 'dict' to 'StructuredDataDict' since it's supposed to be a storage class.  Given that we were only testing to see if it was something else (like 'TaskMetadata'), this didn't matter, but it was confusing.
> DM-39760: Fix bugs in test pipeline task storage conversions.

- doc/changes/DM-39661.api.rst
- doc/changes/DM-39661.feature.rst
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cli/script/run_qbb.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_cmdLineFwk.py
Requires lsst/pipe_base#344
Add `--cores-per-quantum` and `--memory-per-quantum` options.
> DM-39661: Add support for ExecutionResources

- doc/lsst.ctrl.mpexec/configuring-pipetask-tasks.rst
- requirements.txt
> DM-35579: Update import pointer in docs for pipelines_check

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/conf.py
- pyproject.toml
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/dotTools.py
- python/lsst/ctrl/mpexec/executionGraphFixup.py
- python/lsst/ctrl/mpexec/reports.py
- python/lsst/ctrl/mpexec/showInfo.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/util.py
- tests/test_cliCmdCleanup.py
- tests/test_cliCmdPurge.py
- tests/test_cliCmdUpdateGraphRun.py
- tests/test_cliScript.py
- tests/test_cliUtils.py
- tests/test_cmdLineFwk.py
- tests/test_dotTools.py
- tests/test_executors.py
- tests/test_reports.py
- tests/test_separablePipelineExecutor.py
- tests/test_simple_pipeline_executor.py
- tests/test_taskFactory.py
> DM-39857: Remove --flake8 option and add ruff config

- .github/workflows/do_not_merge.yaml
- python/lsst/ctrl/mpexec/cmdLineFwk.py
> DM-39915: Use internal butler datastore property in constructor

- doc/changes/DM-40254.feature.md
- doc/changes/README.rst
- python/lsst/ctrl/mpexec/showInfo.py
The output now includes more complete information about dataset refs and also their related datastore records if they appear in the quantum graph.
> DM-40254: Expand output of `--show=graph` option

- python/lsst/ctrl/mpexec/cli/utils.py
- tests/test_cliScript.py
> DM-33027: miscellaneous fixes from PipelineGraph work

- .github/workflows/rebase_checker.yaml
- .pre-commit-config.yaml
- mypy.ini
- pyproject.toml
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/utils.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/execFixupDataId.py
- python/lsst/ctrl/mpexec/log_capture.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/reports.py
- python/lsst/ctrl/mpexec/showInfo.py
- tests/test_cmdLineFwk.py
- tests/test_reports.py
> DM-40303: Minor clean ups for pydantic v2

- doc/changes/DM-40332.misc.md
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
> DM-40332: improve logging and simplify existence checks in SingleQuantumExecutor

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
There was a code path that was using the class but which failed because it was only imported during type checking.
> DM-40390: Remove TYPE_CHECKING block to fix DatastoreRecordData import

- tests/test_cmdLineFwk.py
Depends on lsst/pipe_base#368 and lsst/daf_butler#879
> DM-40381: update test expectations in response to QG generation changes upstream

- tests/test_cmdLineFwk.py
Depends on lsst/pipe_base#369 and lsst/daf_butler#882
> DM-40392: Update unit test after fixing QuantumGraph.updateRun

- doc/changes/DM-37140.feature.md
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
> DM-37140: Add rebase option to pipetask

- doc/changes/DM-39779.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/build.py
- python/lsst/ctrl/mpexec/showInfo.py
- tests/test_cmdLineFwk.py
> DM-39779: text-based graph visualization of pipelines

- .pre-commit-config.yaml
- doc/changes/DM-35599.bugfix.rst
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
This stops it shadowing --task.
Requires lsst/daf_butler#888
> DM-35599: Use a transfer option that does not include -t

- mypy.ini
- python/lsst/ctrl/mpexec/cli/script/build.py
- python/lsst/ctrl/mpexec/cli/script/cleanup.py
- python/lsst/ctrl/mpexec/cli/script/purge.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- tests/test_cliCmdCleanup.py
- tests/test_separablePipelineExecutor.py
Butler is now an abstract class, and preferred way to instanciate butlers
is `Butler.from_config`. Execution butler requires a `DirectButler` instance,
updated the code to reflect that (somewhat hackish, but execution butler is
going to disappear any minute now or next year).
> DM-41116: Few updates fiollowing Butler interface change

- tests/test_cmdLineFwk.py
> DM-41235: Update test to use SqlRegistry instead of Registry

- doc/changes/DM-41131.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/__init__.py
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/report.py
- tests/test_cliCmdReport.py
> DM-41131: Add pipetask report on output of a quantum graph

- python/lsst/ctrl/mpexec/preExecInit.py
- tests/test_cmdLineFwk.py
Depends on lsst/daf_butler#899
> DM-41365: Use new Butler get_dataset_type and find_dataset APIs

- python/lsst/ctrl/mpexec/cli/script/report.py
> DM-41321: Add try-except block to manifest checker so that failure to get butler logs does not make error reporting impossible

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .pre-commit-config.yaml
- doc/changes/DM-41832.removal.md
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cli/script/run_qbb.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
Fork became unusable, switching default start method to spawn. Forkserver
option is still available, fork option is kept in CLI for compatibility
but we issue a warning and switch to spawn if fork is given.
> DM-41832: Use spawn as start method, deprecate fork option

- .github/workflows/build.yaml
- tests/test_executors.py
> DM-41904: Enable python 3.12

- doc/changes/DM-41962.bugfix.md
- python/lsst/ctrl/mpexec/preExecInit.py
- tests/test_simple_pipeline_executor.py
PipelineDatasetTypes does not preserve storage classes (that's why it's being deprecated).
> DM-41962: Use storage classes from QG in PreExecInit.

- .pre-commit-config.yaml
- doc/changes/DM-42118.bugfix.rst
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cli/script/run_qbb.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
> DM-42118: Allow run-qbb to have implicit threading disabled

- .github/workflows/build_docs.yaml
- doc/changes/DM-42302.misc.md
- pyproject.toml
- python/lsst/ctrl/mpexec/reports.py
- requirements.txt
> DM-42302: drop support for Pydantic v1

- doc/changes/DM-42376.bugfix.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- tests/test_cmdLineFwk.py
> DM-42376: Fix dump_kwargs TypeError.

- .pre-commit-config.yaml
- doc/changes/DM-42751.api.rst
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
> DM-42751: Add num_proc parameter to SeparablePipelineExecutor.run_pipeline()

- doc/changes/DM-41606.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/report.py
- tests/test_cliCmdReport.py
- types.txt
> DM-41606: Option to output pipetask report info to command line

- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
> DM-43060: Let checkExistingOutputs work without a full butler

- doc/changes/DM-43363.bugfix.md
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- tests/test_cliCmdReport.py
> DM-43363: Remove extraneous files from pipetask report tests

- doc/changes/DM-43484.bugfix.md
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- run_err.yaml
> DM-43484: Fix BPS auto-retries and add support for testing that in ci_middleware

- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/dotTools.py
- python/lsst/ctrl/mpexec/log_capture.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/preExecInit.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/showInfo.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- python/lsst/ctrl/mpexec/taskFactory.py
- python/lsst/ctrl/mpexec/util.py
- requirements.txt
- tests/test_cmdLineFwk.py
- tests/test_executors.py
- tests/test_separablePipelineExecutor.py
- tests/test_simple_pipeline_executor.py
- tests/test_taskFactory.py
- types.txt
> DM-40441: first batch of deprecations from RFC-949

- .github/workflows/build.yaml
- doc/changes/DM-41542.feature.rst
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/reports.py
- tests/test_cliCmdQgraph.py
- tests/test_executors.py
- tests/test_reports.py
> DM-41542:  Add --summary option to pipetask qgraph.

- doc/changes/DM-44091.bugfix.md
- python/lsst/ctrl/mpexec/cli/script/report.py
- tests/test_cliCmdReport.py
> DM-44091: For len(failed_quanta)>5, display counts and not data_ids

- doc/changes/DM-44647.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/build.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/showInfo.py
- tests/test_cmdLineFwk.py
This commit moves the pipeline-dot build logic from cmdLineFwk into cli/script/build.py.
As part of this commit, a switch to using the same back-end display args parser as --show pipeline-graph is also made.
> DM-44647: Move pipeline-dot build from cmdLineFwk to builder

- doc/changes/DM-44368.feature.md
- python/lsst/ctrl/mpexec/cli/script/report.py
- tests/test_cliCmdReport.py
Depends on lsst/pipe_base#424.
> DM-44368: Include number of expected instances in pipetask report task-level summary

- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_executors.py
This should solve an issue with exceptions happening at unpredictable locations in a SingleQuantumExecutor class. MPGraphExecutor in a single-process mode should also behave reasonably for random exceptions. Multi-process mode has more complex internal state. If a client of the code catches an exception and tries to reuse the executor, the state may be inconsistent, depending on where the exception happens.
> DM-45340: Improve exception handling in quantum executors

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/reports.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
This avoids unexpected process exits from SingleGraphExecutors level. MPGraphExecutor is a better place to handle application-level logic, potentially CmdLineFwk would be even better location, but some context is missing at that level.
> DM-45724: Move handling of exiting exceptions to MPGraphExecutor

- .pre-commit-config.yaml
- doc/changes/DM-45894.bugfix.md
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
With run-qbb when dimension universe is not the default one, we need
to make sure that that universe is instantiated from a configuration
in a subprocess before unpickling anything that requires that universe.
The fix uses butler factory to do that, using its unpickle method,
and there is some complicated logic in executors to make sure that
unpickling of that factory happens first thing in a subprocess.
There may be an easier way to enforce that but it would require
interface changes for MPGraphExecutor or SingleQuantumExecutor.
Subprocess parameters are now pickled manually to guarantee that
logging is initialized properly in a subprocess before any complex
unpickling happens.
> DM-45894: Fix dimension universe instantiation in subprocesses

- doc/changes/DM-44488.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/run.py
- python/lsst/ctrl/mpexec/cli/script/run_qbb.py
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_simple_pipeline_executor.py
> DM-44488: handle new pipe_base exception types in executors

- tests/test_cmdLineFwk.py
This PR adjusts the unit tests for some behavior changes added in lsst/pipe_base#440.
> DM-45722: CRITICAL logs on empty quantum graph

- python/lsst/ctrl/mpexec/cmdLineFwk.py
> DM-45933: fix longstanding bad argument type

- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/preExecInit.py
- tests/test_execution_storage_class_conversion.py
> DM-38041: delegate to new pre-exec-init implementations in pipe_base

- doc/changes/DM-41711.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/__init__.py
- python/lsst/ctrl/mpexec/cli/script/report.py
- requirements.txt
- tests/test_cliCmdReport.py
> DM-41711: Upgrade QuantumGraphExecutionReport to handle multiple overlapping graphs

- doc/changes/DM-46525.misc.md
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_simple_pipeline_executor.py
> DM-46525: switch back to raising on partial output errors by default

- doc/changes/DM-46689.bugfix.md
- python/lsst/ctrl/mpexec/cli/script/report.py
> DM-46689: Check for list index before comparing to previous in pipetask report cli

- python/lsst/ctrl/mpexec/cli/script/cleanup.py
- python/lsst/ctrl/mpexec/separablePipelineExecutor.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
Stop using Butler behavior that was deprecated in RFC-1040.
> DM-46599: Stop using deprecated Butler methods

- doc/changes/DM-41605.feature.md
- python/lsst/ctrl/mpexec/cli/cmd/__init__.py
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/script/__init__.py
- python/lsst/ctrl/mpexec/cli/script/report.py
- requirements.txt
- tests/test_cliCmdReport.py
> DM-41605: Command-line aggregator for pipetask report

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- doc/changes/DM-47482.misc.md
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
> DM-47482: Remove explicit garbage collection

- doc/changes/DM-47159.bugfix.md
- pyproject.toml
- python/lsst/ctrl/mpexec/cli/cmd/commands.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- tests/test_cliScript.py
- Makes coverage import optional and lazy-loads it.
- Bump minimum Python to 3.11 (matching dependency for `daf_butler`).
- Add packaging extra option for coverage; i.e., pip users can specify `pip install lsst-ctrl-mpexec[coverage]`
> DM-48159 : Make Coverage import optional

- doc/changes/DM-40242.misc.md
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_simple_pipeline_executor.py
> DM-40242: skip existence checks for quantum inputs that have datastore records

- python/lsst/ctrl/mpexec/cli/opt/optionGroups.py
- python/lsst/ctrl/mpexec/cli/opt/options.py
- python/lsst/ctrl/mpexec/cli/script/build.py
- python/lsst/ctrl/mpexec/cli/script/qgraph.py
- tests/test_cliScript.py
> DM-46503: Implement Mermaid for pipeline and quantum graph visualization

- doc/changes/DM-47730.feature.md
- python/lsst/ctrl/mpexec/cli/script/report.py
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- tests/test_simple_pipeline_executor.py
> DM-47730: add "success caveats" system to report on NoWorkFound and similar cases

- .pre-commit-config.yaml
- doc/changes/DM-35396.api.rst
- doc/changes/DM-35396.feature.rst
- python/lsst/ctrl/mpexec/cmdLineFwk.py
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
- python/lsst/ctrl/mpexec/quantumGraphExecutor.py
- python/lsst/ctrl/mpexec/singleQuantumExecutor.py
- python/lsst/ctrl/mpexec/util.py
- tests/test_cliCmdCleanup.py
- tests/test_cliCmdPurge.py
- tests/test_cliUtils.py
- tests/test_cmdLineFwk.py
- tests/test_executors.py
- tests/test_preExecInit.py
Requires lsst/pipe_base#464 and lsst/daf_butler#1147
> DM-35396: Pass quantum ID down to executor so it can be used in provenance

- pyproject.toml
- python/lsst/ctrl/mpexec/cmdLineFwk.py
Astropy's Table.pformat_all() is now deprecated -- Table.pformat() is an exact replacement as of Astropy v7
> DM-49197: Fix astropy pformat_all deprecation

- doc/changes/DM-49095.bugfix.rst
- python/lsst/ctrl/mpexec/mpGraphExecutor.py
Not enough arguments for format string.
> DM-49095: MPGraphExecutor: fix failure to fail

- doc/changes/DM-48482.feature.rst
- python/lsst/ctrl/mpexec/cli/script/build.py
> DM-48482: Build image rendering around `mermaid-py` for Mermaid diagrams

- python/lsst/ctrl/mpexec/cmdLineFwk.py
pipetask run was sharing a cache but run-qbb was not.
> DM-49870: Enable shared datastore cache in QBB execution

- doc/changes/SP-2103.feature.md
- python/lsst/ctrl/mpexec/simple_pipeline_executor.py
- tests/pipeline_simple.yaml
- tests/test_simple_pipeline_executor.py
*still in progress* (marked as draft)
> SP-2103: add use_local_butler to ctrl_mpexec
